### ISSUE TITLE
Make SUBRIP_SUBTITLE_TIME inherit from COMPARABLE

### ISSUE THREAD

**Issue by nricci** [nmaguirre/eiffel-subtitle-converter#113]
It seems that there is no "nice" way of asserting order relationships between to SUBRIP_SUBTITLE_TIME objects. The proposal is to make the class inherit from COMPARABLE so the standard comparison operators (i.e. <, >, <=, >=) will be available.

**Comment by nmaguirre** [comment]
I agree completely!

N

**Comment by dahue** [comment]
Solved in 8576ac63f7a2ee052735e0aecfc1a6b2a89312bc

**Comment by andruvetto** [comment]
Fixed in f7354f7479. Redefine " is_equal " was not necessary

**Comment by andruvetto** [comment]
fixed in c6c37da

**Comment by dahue** [comment]
@andruvetto 
Since is_less is inherited from the deferred class COMPARABLE there is no need for a redefinition.
The new implementation of is_less is not right due to that just compares if the first object has less milliseconds than the other but never checks hours, minutes and seconds.

**Comment by andruvetto** [comment]
@dahue 
All routines are inherited from "comparable" but the only routine that must be redefined is "is_less" because ">", "<=" "> =" and "is_equal" are defined on the basis of this. The implementation is correct because it makes time to milliseconds and compared.

**Comment by dahue** [comment]
Actually is not well implemented. The comparison right now is "Current.milliseconds < other.milliseconds" and it should be "Current.time_milliseconds < other.time_milliseconds", I already commited two new tests that prove my point.
@nmaguirre I unassign myself and assign @andruvetto to this issue due to he modified my initial implementation with no notification. So I'm no longer responsible for this issue.

**Comment by andruvetto** [comment]
Sorry you are right. I fixed in 3c0a31d.

**Comment by nricci** [comment]
This is still wrong. For instance, if I were to compare 00:00:01:0001 < 00:00:00:0002 it would be true even though it is not the case. You should take into account seconds, minutes and hours too.

**Comment by andruvetto** [comment]
@nricci Look at the implementation of "time_milliseconds", return hours_3600000 + minutes_60000 + seconds*1000 + milliseconds. So hours, minutes, seconds and milliseconds are compared

**Comment by nricci** [comment]
Yes, you are right. Didn't notice that sorry.
