### ISSUE TITLE
Missing implementation for routine add_subtitle_item.MICRODVD_SUBTITLE

### ISSUE THREAD

**Issue by gamassimino** [nmaguirre/eiffel-subtitle-converter#20]

**Comment by gamassimino** [comment]
solved in rev. 314608e

**Comment by nmaguirre** [comment]
Implementation is wrong. Calling a feature (make) without the appropriate number of parameters. Project does not compile due to this problem. Correct asap. Removing 'resolved'.

**Comment by nmaguirre** [comment]
This implementation actually has MANY problems. You are trying to access with write privileges some local attributes. This is forbidden in Eiffel. Correct asap.

**Comment by nmaguirre** [comment]
You are also referring to an attribute that does not exist (item). Please compile before committing.

**Comment by dromero19** [comment]
Also you need to correct the indentation of the routine, doesn't follow the indentation of the class.

**Comment by gamassimino** [comment]
sorry, fixed in rev. 1b6b1ba

**Comment by nmaguirre** [comment]
Loop condition is wrong. In the declaration of local variables, separate ':' from the type. Constants (True, False, etc) should have the first letter as a capital letter. Removing the 'resolved' tag.

**Comment by gamassimino** [comment]
fixed in rev. c32d78f

**Comment by gamassimino** [comment]
sorry, the correct #commit is 3a9d063

**Comment by gamassimino** [comment]
fixed in rev. fdd95c1

**Comment by gamassimino** [comment]
changed in rev. 722a322

**Comment by saiema** [comment]
Missing condition in precondition, start_frame argument should be greater or equal than zero (>= 0)

**Comment by nricci** [comment]
This appears to be working incorrectly. The tests fail. Please make sure that this feature is working as it is very important to the application functionality.

**Comment by gamassimino** [comment]
I don't understand why you say "Missing condition in precondition", in this issue I'm working in a the implementation of the feature, not in the specification.

**Comment by gamassimino** [comment]
bug fixed in rev. ba09002

**Comment by saiema** [comment]
Sorry, My bad. I'll go see the precondition issue.

**Comment by saiema** [comment]
This implementation seems to allow to do the following

given a subtitle with [(0,1,"hola"), (2,3,"chau")]
call add_subtitle_item(2,4,"bug")

given a subtitle with [(0,1,"hola"), (4,5,"chau")]
call add_subtitle_item(2, 4, "bug")

You should use **MICRODVD_SUBTITLE.free_time_frame** as a precondition

**Comment by gamassimino** [comment]
ok but this issues correspond to implementation
the issue of the precondition for this feature was #37
solved in rev. 82a58f3

**Comment by saiema** [comment]
My bad for the correction of the precondition in this issue, but the correction about implementation was valid although it was fixed by fixing the precondition.

**Comment by mromina** [comment]
The routine doesn't include the case when you want to add an item at the head of the list. Check it with the test in this rev. 47fa1bb.  This test fail.

**Comment by gamassimino** [comment]
ok, check it now
fixed in rev. 3372ed1

**Comment by gamassimino** [comment]
sorry, this is the correct solution 4165f02

**Comment by nicodomgz** [comment]
This implementation is still wrong. I did the following valid test: #221  and didn't pass.

**Comment by gamassimino** [comment]
fixed in rev. e6480f5
