### ISSUE TITLE
Missing implementation for routine remove_items.MICRODVD_SUBTITLE

### ISSUE THREAD

**Issue by nicodomgz** [nmaguirre/eiffel-subtitle-converter#24]
Routine remove_items from class MICRODVD_SUBTITLE has an empty implementation. This routine must be implemented, guided by its textual description.

**Comment by nicodomgz** [comment]
Solved in rev  4246748

**Comment by nmaguirre** [comment]
Loop condition is wrong. Please notice that comparing by <= in the loop condition will prevent from removing an item that should be removed. Removing 'resolved' label.

**Comment by nicodomgz** [comment]
Solved in rev.  4e52ab3

**Comment by nmaguirre** [comment]
Still wrong. You have a border condition. What if a subtitle item stops exactly at the same time as stop_frame?

**Comment by nicodomgz** [comment]
Solved in rev.  a6966c4

**Comment by nricci** [comment]
I'm not sure that  stop_frame > items.item.stop_frame is right. Shouldn't it be the other way around? I mean for a sufficiently large stop_frame it will always be the case. Nevertheless, the test for your method is failing. Make sure that your method works fine, as it is very important for the app functionality.

**Comment by nicodomgz** [comment]
I think that stop_frame > items.item.stop_frame is right. the test for this routine is falling in add_subtitle_item method from MICRODVD_SUBTITLE Class.

the output of test shows " test routine: exceptional (Postcondition violation in MICRODVD_SUBTITLE.add_subtitle_item) "

**Comment by nricci** [comment]
Ok, I'm closing this for the time being. We'll wait for the other features to work correctly.
